//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.15 at 05:06:51 PM GMT 
//


package org.enterprise_architecture.essential.viewercache;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="cachevariables" type="{http://www.enterprise-architecture.org/essential/viewercache}variables"/>
 *         &lt;element name="cachedirectories" type="{http://www.enterprise-architecture.org/essential/viewercache}directories"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "cachevariables",
    "cachedirectories"
})
@XmlRootElement(name = "viewercache")
public class Viewercache {

    @XmlElement(required = true)
    protected Variables cachevariables;
    @XmlElement(required = true)
    protected Directories cachedirectories;

    /**
     * Gets the value of the cachevariables property.
     * 
     * @return
     *     possible object is
     *     {@link Variables }
     *     
     */
    public Variables getCachevariables() {
        return cachevariables;
    }

    /**
     * Sets the value of the cachevariables property.
     * 
     * @param value
     *     allowed object is
     *     {@link Variables }
     *     
     */
    public void setCachevariables(Variables value) {
        this.cachevariables = value;
    }

    /**
     * Gets the value of the cachedirectories property.
     * 
     * @return
     *     possible object is
     *     {@link Directories }
     *     
     */
    public Directories getCachedirectories() {
        return cachedirectories;
    }

    /**
     * Sets the value of the cachedirectories property.
     * 
     * @param value
     *     allowed object is
     *     {@link Directories }
     *     
     */
    public void setCachedirectories(Directories value) {
        this.cachedirectories = value;
    }

}
