//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.15 at 05:06:51 PM GMT 
//


package org.enterprise_architecture.essential.viewercache;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for whenToClear.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="whenToClear">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="pre"/>
 *     &lt;enumeration value="post"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "whenToClear")
@XmlEnum
public enum WhenToClear {

    @XmlEnumValue("pre")
    PRE("pre"),
    @XmlEnumValue("post")
    POST("post");
    private final String value;

    WhenToClear(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static WhenToClear fromValue(String v) {
        for (WhenToClear c: WhenToClear.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
