//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.01.31 at 02:42:01 PM GMT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.enterprise-architecture.org/essential/pagehistory", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.enterprise_architecture.essential.pagehistory;
