//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.17 at 04:47:16 PM BST 
//


package org.enterprise_architecture.essential.vieweruserdata;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for classificationTypeValues.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="classificationTypeValues">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="read"/>
 *     &lt;enumeration value="edit"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "classificationTypeValues")
@XmlEnum
public enum ClassificationTypeValues {

    @XmlEnumValue("read")
    READ("read"),
    @XmlEnumValue("edit")
    EDIT("edit");
    private final String value;

    ClassificationTypeValues(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ClassificationTypeValues fromValue(String v) {
        for (ClassificationTypeValues c: ClassificationTypeValues.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
