//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.17 at 04:47:16 PM BST 
//


package org.enterprise_architecture.essential.vieweruserdata;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="uri" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="firstname" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="lastname" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="email" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="viewers" type="{http://www.enterprise-architecture.org/essential/vieweruserdata}viewerURLList" minOccurs="0"/>
 *         &lt;element name="clearanceList" type="{http://www.enterprise-architecture.org/essential/vieweruserdata}clearanceList"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "uri",
    "firstname",
    "lastname",
    "email",
    "viewers",
    "clearanceList"
})
@XmlRootElement(name = "user")
public class User {

    @XmlElement(required = true)
    protected String uri;
    @XmlElement(required = true)
    protected String firstname;
    @XmlElement(required = true)
    protected String lastname;
    @XmlElement(required = true)
    protected String email;
    protected ViewerURLList viewers;
    @XmlElement(required = true)
    protected ClearanceList clearanceList;

    /**
     * Gets the value of the uri property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUri() {
        return uri;
    }

    /**
     * Sets the value of the uri property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUri(String value) {
        this.uri = value;
    }

    /**
     * Gets the value of the firstname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFirstname() {
        return firstname;
    }

    /**
     * Sets the value of the firstname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFirstname(String value) {
        this.firstname = value;
    }

    /**
     * Gets the value of the lastname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastname() {
        return lastname;
    }

    /**
     * Sets the value of the lastname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastname(String value) {
        this.lastname = value;
    }

    /**
     * Gets the value of the email property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmail() {
        return email;
    }

    /**
     * Sets the value of the email property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmail(String value) {
        this.email = value;
    }

    /**
     * Gets the value of the viewers property.
     * 
     * @return
     *     possible object is
     *     {@link ViewerURLList }
     *     
     */
    public ViewerURLList getViewers() {
        return viewers;
    }

    /**
     * Sets the value of the viewers property.
     * 
     * @param value
     *     allowed object is
     *     {@link ViewerURLList }
     *     
     */
    public void setViewers(ViewerURLList value) {
        this.viewers = value;
    }

    /**
     * Gets the value of the clearanceList property.
     * 
     * @return
     *     possible object is
     *     {@link ClearanceList }
     *     
     */
    public ClearanceList getClearanceList() {
        return clearanceList;
    }

    /**
     * Sets the value of the clearanceList property.
     * 
     * @param value
     *     allowed object is
     *     {@link ClearanceList }
     *     
     */
    public void setClearanceList(ClearanceList value) {
        this.clearanceList = value;
    }

}
