//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.30 at 12:54:44 PM BST 
//


package org.enterprise_architecture.essential.viewclassification;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for defaultClassificationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="defaultClassificationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence minOccurs="0">
 *         &lt;element name="readClassification" type="{http://www.enterprise-architecture.org/essential/viewerclassification}classificationType" minOccurs="0"/>
 *         &lt;element name="editClassification" type="{http://www.enterprise-architecture.org/essential/viewerclassification}classificationType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "defaultClassificationType", propOrder = {
    "readClassification",
    "editClassification"
})
public class DefaultClassificationType {

    protected ClassificationType readClassification;
    protected ClassificationType editClassification;

    /**
     * Gets the value of the readClassification property.
     * 
     * @return
     *     possible object is
     *     {@link ClassificationType }
     *     
     */
    public ClassificationType getReadClassification() {
        return readClassification;
    }

    /**
     * Sets the value of the readClassification property.
     * 
     * @param value
     *     allowed object is
     *     {@link ClassificationType }
     *     
     */
    public void setReadClassification(ClassificationType value) {
        this.readClassification = value;
    }

    /**
     * Gets the value of the editClassification property.
     * 
     * @return
     *     possible object is
     *     {@link ClassificationType }
     *     
     */
    public ClassificationType getEditClassification() {
        return editClassification;
    }

    /**
     * Sets the value of the editClassification property.
     * 
     * @param value
     *     allowed object is
     *     {@link ClassificationType }
     *     
     */
    public void setEditClassification(ClassificationType value) {
        this.editClassification = value;
    }

}
