//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.30 at 12:54:44 PM BST 
//


package org.enterprise_architecture.essential.viewclassification;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.enterprise_architecture.essential.viewerclassification package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.enterprise_architecture.essential.viewerclassification
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Viewclassification }
     * 
     */
    public Viewclassification createViewclassification() {
        return new Viewclassification();
    }

    /**
     * Create an instance of {@link DefaultClassificationType }
     * 
     */
    public DefaultClassificationType createDefaultClassificationType() {
        return new DefaultClassificationType();
    }

    /**
     * Create an instance of {@link ClassificationGroupType }
     * 
     */
    public ClassificationGroupType createClassificationGroupType() {
        return new ClassificationGroupType();
    }

    /**
     * Create an instance of {@link ViewListType }
     * 
     */
    public ViewListType createViewListType() {
        return new ViewListType();
    }

    /**
     * Create an instance of {@link ViewType }
     * 
     */
    public ViewType createViewType() {
        return new ViewType();
    }

    /**
     * Create an instance of {@link ClassificationType }
     * 
     */
    public ClassificationType createClassificationType() {
        return new ClassificationType();
    }

}
