//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.30 at 12:54:44 PM BST 
//


package org.enterprise_architecture.essential.viewclassification;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="defaultClassification" type="{http://www.enterprise-architecture.org/essential/viewerclassification}defaultClassificationType" minOccurs="0"/>
 *         &lt;element name="classificationGroups" type="{http://www.enterprise-architecture.org/essential/viewerclassification}classificationGroupType"/>
 *         &lt;element name="views" type="{http://www.enterprise-architecture.org/essential/viewerclassification}viewListType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "defaultClassification",
    "classificationGroups",
    "views"
})
@XmlRootElement(name = "viewclassification")
public class Viewclassification {

    protected DefaultClassificationType defaultClassification;
    @XmlElement(required = true)
    protected ClassificationGroupType classificationGroups;
    @XmlElement(required = true)
    protected ViewListType views;

    /**
     * Gets the value of the defaultClassification property.
     * 
     * @return
     *     possible object is
     *     {@link DefaultClassificationType }
     *     
     */
    public DefaultClassificationType getDefaultClassification() {
        return defaultClassification;
    }

    /**
     * Sets the value of the defaultClassification property.
     * 
     * @param value
     *     allowed object is
     *     {@link DefaultClassificationType }
     *     
     */
    public void setDefaultClassification(DefaultClassificationType value) {
        this.defaultClassification = value;
    }

    /**
     * Gets the value of the classificationGroups property.
     * 
     * @return
     *     possible object is
     *     {@link ClassificationGroupType }
     *     
     */
    public ClassificationGroupType getClassificationGroups() {
        return classificationGroups;
    }

    /**
     * Sets the value of the classificationGroups property.
     * 
     * @param value
     *     allowed object is
     *     {@link ClassificationGroupType }
     *     
     */
    public void setClassificationGroups(ClassificationGroupType value) {
        this.classificationGroups = value;
    }

    /**
     * Gets the value of the views property.
     * 
     * @return
     *     possible object is
     *     {@link ViewListType }
     *     
     */
    public ViewListType getViews() {
        return views;
    }

    /**
     * Sets the value of the views property.
     * 
     * @param value
     *     allowed object is
     *     {@link ViewListType }
     *     
     */
    public void setViews(ViewListType value) {
        this.views = value;
    }

}
