//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.30 at 12:54:44 PM BST 
//


package org.enterprise_architecture.essential.viewclassification;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for viewType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="viewType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="template" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="viewClassification" type="{http://www.enterprise-architecture.org/essential/viewerclassification}classificationGroupType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "viewType", propOrder = {
    "template",
    "viewClassification"
})
public class ViewType {

    @XmlElement(required = true)
    protected String template;
    @XmlElement(required = true)
    protected ClassificationGroupType viewClassification;

    /**
     * Gets the value of the template property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTemplate() {
        return template;
    }

    /**
     * Sets the value of the template property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTemplate(String value) {
        this.template = value;
    }

    /**
     * Gets the value of the viewClassification property.
     * 
     * @return
     *     possible object is
     *     {@link ClassificationGroupType }
     *     
     */
    public ClassificationGroupType getViewClassification() {
        return viewClassification;
    }

    /**
     * Sets the value of the viewClassification property.
     * 
     * @param value
     *     allowed object is
     *     {@link ClassificationGroupType }
     *     
     */
    public void setViewClassification(ClassificationGroupType value) {
        this.viewClassification = value;
    }

}
